name: app_environment
channels:
  - snowflake
  - conda-forge
dependencies:
  - python=3.11.*
  - streamlit
  - pandas
  - openpyxl
  - xlsxwriter  # ✅ Required to write .xlsx files
  - snowflake-snowpark-python
